import { Customer } from "../types";

export const customersData: Customer[] = [
  {
    id: 1,
    company: "Acme Corporation",
    contact: "Alice Johnson",
    title: "CEO",
    address: "123 Acme Ave",
    city: "San Francisco",
    postalCode: "94101",
    region: "CA",
    country: "USA",
    phone: "+1 415-555-1234",
  },
  {
    id: 2,
    company: "Globex Inc.",
    contact: "Bob Brown",
    title: "CTO",
    address: "456 Globex Road",
    city: "New York",
    postalCode: "10001",
    region: "NY",
    country: "USA",
    phone: "+1 212-555-5678",
  },
  {
    id: 3,
    company: "Initech",
    contact: "Charlie Davis",
    title: "CFO",
    address: "789 Initech Blvd",
    city: "Chicago",
    postalCode: "60601",
    region: "IL",
    country: "USA",
    phone: "+1 312-555-9012",
  },
  {
    id: 4,
    company: "Umbrella Corp.",
    contact: "Diana Evans",
    title: "COO",
    address: "123 Umbrella Way",
    city: "Tokyo",
    postalCode: "100-0001",
    region: "TYO",
    country: "Japan",
    phone: "+81 3-1234-5678",
  },
  {
    id: 5,
    company: "Hooli",
    contact: "Edward Franklin",
    title: "CMO",
    address: "456 Hooli Blvd",
    city: "Los Angeles",
    postalCode: "90001",
    region: "CA",
    country: "USA",
    phone: "+1 310-555-7890",
  },
];
