import { Supplier } from "../types";

export const suppliersData: Supplier[] = [
  { 
    id: 1, 
    company: "Exotic Liquids", 
    contact: "Charlotte Cooper", 
    title: "Purchasing Manager", 
    address: "49 Gilbert St.",
    city: "London", 
    postalCode: "EC1 4SD",
    region: "London",
    country: "UK", 
    phone: "(171) 555-2222",
  },
  { 
    id: 2, 
    company: "New Orleans Cajun Delights", 
    contact: "Shelley Burke", 
    title: "Order Administrator", 
    address: "P.O. Box 78934",
    city: "New Orleans", 
    postalCode: "70117",
    region: "LA",
    country: "USA", 
    phone: "(100) 555-4822",
  },
  { 
    id: 3, 
    company: "Grandma Kelly's Homestead", 
    contact: "Regina Murphy", 
    title: "Sales Representative", 
    address: "707 Oxford Rd.",
    city: "Ann Arbor", 
    postalCode: "48104",
    region: "MI",
    country: "USA", 
    phone: "(313) 555-5735",
  },
  { 
    id: 4, 
    company: "Tokyo Traders", 
    contact: "Yoshi Nagase", 
    title: "Marketing Manager", 
    address: "9-8 Sekimai Musashino-shi",
    city: "Tokyo", 
    postalCode: "100",
    region: "Tokyo",
    country: "Japan", 
    phone: "(03) 3555-5011",
  },
  { 
    id: 5, 
    company: "Cooperativa de Quesos 'Las Cabras'", 
    contact: "Antonio del Valle Saavedra", 
    title: "Export Administrator", 
    address: "Calle del Rosal 4",
    city: "Oviedo", 
    postalCode: "33007",
    region: "Asturias",
    country: "Spain", 
    phone: "(98) 598 76 54",
  },
  { 
    id: 6, 
    company: "Mayumi's", 
    contact: "Mayumi Ohno", 
    title: "Marketing Representative", 
    address: "92 Setsuko Chuo-ku",
    city: "Osaka", 
    postalCode: "545",
    region: "Osaka",
    country: "Japan", 
    phone: "(06) 431-7877",
  },
  
]